namespace RemoteLink.Shared.Models;

/// <summary>
/// A pairing request sent from a client device to the host.
/// Contains the client's identity and the PIN entered by the user.
/// </summary>
public class PairingRequest
{
    /// <summary>Unique identifier of the requesting client device.</summary>
    public string ClientDeviceId { get; set; } = string.Empty;

    /// <summary>Human-readable name of the requesting client device.</summary>
    public string ClientDeviceName { get; set; } = string.Empty;

    /// <summary>PIN entered by the client user (6-digit numeric string).</summary>
    public string Pin { get; set; } = string.Empty;

    /// <summary>UTC timestamp when the request was sent.</summary>
    public DateTime RequestedAt { get; set; }
}

/// <summary>
/// A pairing response sent from the host back to the client.
/// Indicates whether pairing was accepted and, on success, carries a session token.
/// </summary>
public class PairingResponse
{
    /// <summary>Whether the pairing was accepted by the host.</summary>
    public bool Success { get; set; }

    /// <summary>Reason for failure; null when <see cref="Success"/> is true.</summary>
    public PairingFailureReason? FailureReason { get; set; }

    /// <summary>
    /// Opaque session token generated by the host on successful pairing.
    /// The client should present this token in subsequent session messages.
    /// Null on failure.
    /// </summary>
    public string? SessionToken { get; set; }

    /// <summary>Human-readable message (for logging / UI display).</summary>
    public string Message { get; set; } = string.Empty;
}

/// <summary>Reason a pairing attempt was rejected.</summary>
public enum PairingFailureReason
{
    /// <summary>The supplied PIN does not match the host's current PIN.</summary>
    InvalidPin,

    /// <summary>The host's PIN has expired (> 5 minutes old).</summary>
    PinExpired,

    /// <summary>Too many failed attempts; further attempts are blocked until the PIN is refreshed.</summary>
    TooManyAttempts,

    /// <summary>The host explicitly refused the connection (future: manual deny UI).</summary>
    HostRefused
}

/// <summary>
/// Result of a single pairing attempt, used as the event argument for
/// <see cref="Interfaces.IPairingService.PairingAttempted"/>.
/// </summary>
public class PairingAttemptResult
{
    /// <summary>Whether the attempt succeeded.</summary>
    public bool Success { get; set; }

    /// <summary>Reason for failure; null on success.</summary>
    public PairingFailureReason? FailureReason { get; set; }

    /// <summary>Client device identifier from the request (if available).</summary>
    public string? ClientDeviceId { get; set; }
}
